/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timer;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
/**
 *
 * @author 2ndyrGroupC
 */
public class Timer extends javax.swing.JFrame {

    static int seconds = 0;
    static int minutes = 0;
    static int hours = 0;
    static int secondsCountDown = 10;
    static int secondsCountUp = 0;
    
    static boolean stateStopWatch = true;
    static boolean stateCountDown = true;
    static boolean stateCountUp = true;

    /**
     * Creates new form Timers
     */
    public Timer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        CountUp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        countup = new javax.swing.JLabel();
        startBtnCounterUp = new javax.swing.JButton();
        stopBtnCounterUp = new javax.swing.JButton();
        resetBtnCounterUp = new javax.swing.JButton();
        CurrentTime = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        GetCurrentTime = new javax.swing.JButton();
        testCurrentTime = new javax.swing.JLabel();
        CountDown = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        startBtnCounterDown = new javax.swing.JButton();
        stopBtnCounterDown = new javax.swing.JButton();
        resetBtnCounterDown = new javax.swing.JButton();
        countdown = new javax.swing.JLabel();
        StopWatch = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        startBtnStopWatch = new javax.swing.JButton();
        stopBtnStopWatch = new javax.swing.JButton();
        resetBtnStopWatch = new javax.swing.JButton();
        hourStopWatch = new javax.swing.JLabel();
        secondStopWatch = new javax.swing.JLabel();
        minuteStopWatch = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CountUp.setBackground(new java.awt.Color(44,62,80));
        CountUp.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        CountUp.setFocusCycleRoot(true);

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setText("COUNT UP");

        countup.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        countup.setText("0");

        startBtnCounterUp.setText("START");
        startBtnCounterUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnCounterUpActionPerformed(evt);
            }
        });

        stopBtnCounterUp.setText("STOP");
        stopBtnCounterUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnCounterUpActionPerformed(evt);
            }
        });

        resetBtnCounterUp.setText("RESET");
        resetBtnCounterUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnCounterUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CountUpLayout = new javax.swing.GroupLayout(CountUp);
        CountUp.setLayout(CountUpLayout);
        CountUpLayout.setHorizontalGroup(
            CountUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CountUpLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(startBtnCounterUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(CountUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CountUpLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CountUpLayout.createSequentialGroup()
                        .addComponent(stopBtnCounterUp)
                        .addGap(29, 29, 29)))
                .addComponent(resetBtnCounterUp)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CountUpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(countup, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        CountUpLayout.setVerticalGroup(
            CountUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CountUpLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(57, 57, 57)
                .addComponent(countup, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(CountUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtnCounterUp)
                    .addComponent(stopBtnCounterUp)
                    .addComponent(resetBtnCounterUp))
                .addGap(24, 24, 24))
        );

        CurrentTime.setBackground(new java.awt.Color(255,51, 51));
        CurrentTime.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("CURRENT TIME");

        GetCurrentTime.setText("GET TIME");
        GetCurrentTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetCurrentTimeActionPerformed(evt);
            }
        });

        testCurrentTime.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        testCurrentTime.setText("0000-00-00 00:00:00");

        javax.swing.GroupLayout CurrentTimeLayout = new javax.swing.GroupLayout(CurrentTime);
        CurrentTime.setLayout(CurrentTimeLayout);
        CurrentTimeLayout.setHorizontalGroup(
            CurrentTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrentTimeLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CurrentTimeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CurrentTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CurrentTimeLayout.createSequentialGroup()
                        .addComponent(testCurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CurrentTimeLayout.createSequentialGroup()
                        .addComponent(GetCurrentTime)
                        .addGap(111, 111, 111))))
        );
        CurrentTimeLayout.setVerticalGroup(
            CurrentTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrentTimeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(64, 64, 64)
                .addComponent(testCurrentTime, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(57, 57, 57)
                .addComponent(GetCurrentTime)
                .addGap(30, 30, 30))
        );

        CountDown.setBackground(new java.awt.Color(51,04,255));
        CountDown.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setText("COUNT DOWN");

        startBtnCounterDown.setText("START");
        startBtnCounterDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnCounterDownActionPerformed(evt);
            }
        });

        stopBtnCounterDown.setText("STOP");
        stopBtnCounterDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnCounterDownActionPerformed(evt);
            }
        });

        resetBtnCounterDown.setText("RESET");
        resetBtnCounterDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnCounterDownActionPerformed(evt);
            }
        });

        countdown.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        countdown.setText("10");

        javax.swing.GroupLayout CountDownLayout = new javax.swing.GroupLayout(CountDown);
        CountDown.setLayout(CountDownLayout);
        CountDownLayout.setHorizontalGroup(
            CountDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CountDownLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(startBtnCounterDown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(stopBtnCounterDown)
                .addGap(40, 40, 40)
                .addComponent(resetBtnCounterDown)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CountDownLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CountDownLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(countdown, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        CountDownLayout.setVerticalGroup(
            CountDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CountDownLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(51, 51, 51)
                .addComponent(countdown, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CountDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtnCounterDown)
                    .addComponent(stopBtnCounterDown)
                    .addComponent(resetBtnCounterDown))
                .addGap(22, 22, 22))
        );

        StopWatch.setBackground(new java.awt.Color(255,102,0));
        StopWatch.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setText("STOPWATCH");

        startBtnStopWatch.setText("START");
        startBtnStopWatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnStopWatchActionPerformed(evt);
            }
        });

        stopBtnStopWatch.setText("STOP");
        stopBtnStopWatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnStopWatchActionPerformed(evt);
            }
        });

        resetBtnStopWatch.setText("RESET");
        resetBtnStopWatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnStopWatchActionPerformed(evt);
            }
        });

        hourStopWatch.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 45)); // NOI18N
        hourStopWatch.setText(" 00");

        secondStopWatch.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 45)); // NOI18N
        secondStopWatch.setText(": 00");

        minuteStopWatch.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 45)); // NOI18N
        minuteStopWatch.setText(": 00");

        javax.swing.GroupLayout StopWatchLayout = new javax.swing.GroupLayout(StopWatch);
        StopWatch.setLayout(StopWatchLayout);
        StopWatchLayout.setHorizontalGroup(
            StopWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StopWatchLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(startBtnStopWatch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StopWatchLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(hourStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StopWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StopWatchLayout.createSequentialGroup()
                        .addComponent(minuteStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(StopWatchLayout.createSequentialGroup()
                        .addGroup(StopWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(StopWatchLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(stopBtnStopWatch)
                                .addGap(31, 31, 31)
                                .addComponent(resetBtnStopWatch)))
                        .addGap(44, 44, 44))))
        );
        StopWatchLayout.setVerticalGroup(
            StopWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StopWatchLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StopWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(StopWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtnStopWatch)
                    .addComponent(stopBtnStopWatch)
                    .addComponent(resetBtnStopWatch))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CountDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StopWatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CountUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CurrentTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CurrentTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StopWatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CountUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CountDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void startBtnStopWatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnStopWatchActionPerformed
        stateStopWatch = true;

        Thread t = new Thread() {
            public void run() {
                for (;;) {
                    if (stateStopWatch == true) {
                        try {
                            sleep(1000);
                            if (seconds == 60) {
                                seconds = 0;
                                minutes++;
                            }
                            if (minutes == 60) {
                                seconds = 0;
                                hours++;
                            }

                            secondStopWatch.setText(": " + seconds);
                            minuteStopWatch.setText(": " + minutes);
                            hourStopWatch.setText("" + hours);
                            seconds++;

                        } catch (InterruptedException e) {
                            System.out.println(e.getMessage());
                        }
                    } else {
                        break;
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_startBtnStopWatchActionPerformed

    private void stopBtnStopWatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnStopWatchActionPerformed
        stateStopWatch = false;
    }//GEN-LAST:event_stopBtnStopWatchActionPerformed

    private void resetBtnStopWatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnStopWatchActionPerformed
        stateStopWatch = false;
        StopWatch.setBackground(Color.yellow);

        seconds = 0;
        minutes = 0;
        hours = 0;

        secondStopWatch.setText(":" + seconds);
        minuteStopWatch.setText(":" + minutes);
        hourStopWatch.setText("" + hours);
    }//GEN-LAST:event_resetBtnStopWatchActionPerformed

    private void startBtnCounterDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnCounterDownActionPerformed

        stateCountDown = true;

        Thread t = new Thread() {
            public void run() {
                for (;;) {
                    if (stateCountDown == true) {
                        try {
                            sleep(1000);
                            if (secondsCountDown != 0) {;
                                secondsCountDown--;
                            } else if (secondsCountDown == 0) {
                                CountDown.setBackground(Color.pink);
                            }
                            countdown.setText(" " + secondsCountDown);

                        } catch (InterruptedException e) {
                            System.out.println(e.getMessage());
                        }
                    } else {
                        break;
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_startBtnCounterDownActionPerformed

    private void startBtnCounterUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnCounterUpActionPerformed

        stateCountUp = true;

        Thread t = new Thread() {
            public void run() {
                for (;;) {
                    if (stateCountUp == true) {
                        try {
                            sleep(1000);
                           secondsCountUp++;
                           if(secondsCountUp == 11){
                               CountUp.setBackground(Color.ORANGE);
                               break;
                           }                          
                            countup.setText(" " + secondsCountUp);
                            
                        } catch (InterruptedException e) {
                            System.out.println(e.getMessage());
                        }
                    } else {
                        break;
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_startBtnCounterUpActionPerformed

    private void GetCurrentTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetCurrentTimeActionPerformed

        Thread t = new Thread() {
            public void run() {
                for (;;) {
                    try {
                        Date date = new Date();
                        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd  hh:mm:ss");
                        testCurrentTime.setText(dateFormat.format(date));
                    } catch(Exception e) {
                        System.out.println(e.getMessage());
                        break;
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_GetCurrentTimeActionPerformed

    private void stopBtnCounterDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnCounterDownActionPerformed
        stateCountDown = false;
    }//GEN-LAST:event_stopBtnCounterDownActionPerformed

    private void resetBtnCounterDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnCounterDownActionPerformed
        stateCountDown = false;
        CountDown.setBackground(Color.red);
        secondsCountDown = 10; 
        countdown.setText(" " + secondsCountDown);
    }//GEN-LAST:event_resetBtnCounterDownActionPerformed

    private void stopBtnCounterUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnCounterUpActionPerformed
        stateCountUp = false;
        
    }//GEN-LAST:event_stopBtnCounterUpActionPerformed

    private void resetBtnCounterUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnCounterUpActionPerformed
        stateCountUp = false;
        CountUp.setBackground(Color.green);
        secondsCountUp = 0; 
        countup.setText(" " + secondsCountUp);
        
        
    }//GEN-LAST:event_resetBtnCounterUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CountDown;
    private javax.swing.JPanel CountUp;
    private javax.swing.JPanel CurrentTime;
    private javax.swing.JButton GetCurrentTime;
    private javax.swing.JPanel StopWatch;
    private javax.swing.JLabel countdown;
    private javax.swing.JLabel countup;
    private javax.swing.JLabel hourStopWatch;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel minuteStopWatch;
    private javax.swing.JButton resetBtnCounterDown;
    private javax.swing.JButton resetBtnCounterUp;
    private javax.swing.JButton resetBtnStopWatch;
    private javax.swing.JLabel secondStopWatch;
    private javax.swing.JButton startBtnCounterDown;
    private javax.swing.JButton startBtnCounterUp;
    private javax.swing.JButton startBtnStopWatch;
    private javax.swing.JButton stopBtnCounterDown;
    private javax.swing.JButton stopBtnCounterUp;
    private javax.swing.JButton stopBtnStopWatch;
    private javax.swing.JLabel testCurrentTime;
    // End of variables declaration//GEN-END:variables
}
